exports.Squad = (req, res) => {
    res.json({
        squad: [
            {
                id: 0,
                img: "https://imgur.com/Wzqjj36.png",
                name: "Edouard Mendy",
                nationality: "Senegal",
                flag: "https://imgur.com/6OJdbaw.png",
                position: "Goalkeeper",
                birth: "01/03/1992 (29)",
                number: "16",
                appearances: "37",
                assists: "0",
                goals: "0",
                info: "Édouard Osoque Mendy (born 1 March 1992) is a professional footballer who plays as a goalkeeper for Premier League club Chelsea. Born and raised in France, he represents Senegal at international level. Starting his career in his native France, Mendy played in the Le Havre academy before signing professional terms with third division Cherbourg in 2011. Mendy was released in 2014, after which he almost quit the game before getting an opportunity with Marseille's reserves. He established himself over the next few seasons at Reims and Rennes before signing for Premier League club Chelsea in 2020. He immediately established himself as the club's new first-choice goalkeeper and kept 16 clean sheets in his first Premier League season. In the same season, Mendy equalled the record held by Santiago Cañizares and Keylor Navas for most clean sheets in a Champions League season with nine, and played an integral part in the road to the final which saw Chelsea beat Manchester City 1–0. Regarded as one of the best goalkeepers across Europe, Mendy has won the UEFA Goalkeeper of the Season in 2021. Eligible to play for Guinea-Bissau, Senegal and France, Mendy initially joined up with Guinea-Bissau in honour of his father, but subsequently switched allegiance to Senegal, where he became the first choice keeper for the 2019 Africa Cup of Nations."
            },
            {
                id: 1,
                img: "https://imgur.com/7WyXsF0.png",
                name: "Kepa Arrizabalaga",
                nationality: "Spain",
                flag: "https://imgur.com/AFxTnIn.png",
                position: "Goalkeeper",
                birth: "03/10/1994 (27)",
                number: "1",
                appearances: "77",
                assists: "0",
                goals: "0",
                info: "Kepa Arrizabalaga Revuelta (born 3 October 1994) is a Spanish professional footballer who plays as a goalkeeper for Premier League club Chelsea and the Spain national team. He is sometimes referred to simply as Kepa. A Basque native, Arrizabalaga began his senior club career with Athletic Bilbao. He played for Basconia, and joined Ponferradina and Real Valladolid on consecutive loans, between 2011 and 2016. He then returned to Bilbao and became a first-team regular; in 2018, he was the subject of a record association football transfer when he moved to Chelsea in a transfer worth €80 million (£72 million), a record fee for a goalkeeper. There, he won the UEFA Europa League, the UEFA Champions League and the UEFA Super Cup. Arrizabalaga won the 2012 European Championship with Spain's under-19 team. He made his senior debut in 2017, and was selected for the 2018 World Cup."
            },
            {
                id: 2,
                img: "https://imgur.com/TmRwoY9.png",
                name: "Marcus Bettinelli",
                nationality: "England",
                flag: "https://imgur.com/xTc0O2G.png",
                position: "Goalkeeper",
                birth: "24/05/1992 (29)",
                number: "13",
                appearances: "7",
                assists: "0",
                goals: "0",
                info: "Marcus Bettinelli (born 24 May 1992) is an English professional footballer who plays as a goalkeeper for Premier League club Chelsea. He has been capped by the England national under-21 team and called up for the senior team."
            },
            {
                id: 3,
                img: "https://imgur.com/IfyW4oq.png",
                name: "Marcos Alonso",
                nationality: "Spain",
                flag: "https://imgur.com/AFxTnIn.png",
                position: "Defender",
                birth: "28/12/1990 (30)",
                number: "3",
                appearances: "157",
                assists: "13",
                goals: "23",
                info: "Marcos Alonso Mendoza (born 28 December 1990) is a Spanish professional footballer who plays as a left back or wing back for Premier League club Chelsea and the Spain national team. Alonso started his career with Real Madrid but went on to make his name with Bolton Wanderers in England and later with Fiorentina in Italy. His success at the latter club led Chelsea to sign him for an estimated £24 million in 2016, going on to win multiple honours with the club including a Premier League and UEFA Champions League title. Alonso made his full debut for Spain in March 2018."
            },
            {
                id: 4,
                img: "https://imgur.com/s2jE9JR.png",
                name: "Cesar Azpilicueta",
                nationality: "Spain",
                flag: "https://imgur.com/AFxTnIn.png",
                position: "Defender",
                birth: "28/08/1989 (32)",
                number: "28",
                appearances: "304",
                assists: "35",
                goals: "9",
                info: "César Azpilicueta Tanco (born 28 August 1989) is a Spanish professional footballer who plays as a right-back or centre-back for Premier League club Chelsea, which he captains, and the Spain national team. A youth product of Osasuna, Azpilicueta spent three seasons in La Liga before switching to Marseille, winning four major honours with the French club. In the summer of 2012, he moved to Chelsea, winning the Europa League in his first season and a domestic double two years later. He has made over 400 appearances for Chelsea and is currently eighth on their list of all-time appearances; Petr Čech is the only non-English person to have played more times for the club. He captained Chelsea to win the Europa League in 2019 and the Champions League in 2021. Azpilicueta earned 55 caps for Spain at youth level in all age groups, and represented the under-21s in two European Championships, winning the 2011 edition. He made his first appearance with the full side in 2013 and was selected for two World Cups as well as Euro 2016 and Euro 2020."
            },
            {
                id: 5,
                img: "https://imgur.com/imp8xrV.png",
                name: "Reece James",
                nationality: "England",
                flag: "https://imgur.com/xTc0O2G.png",
                position: "Defender",
                birth: "08/12/1999 (21)",
                number: "24",
                appearances: "60",
                assists: "6",
                goals: "2",
                info: "Reece James (born 8 December 1999) is an English professional footballer who plays as a right-back for Premier League club Chelsea and the England national team. James joined the Chelsea academy as a youth and turned professional in 2017, a season where he captained the under-18s to victory in the FA Youth Cup and was named Academy Player of the Season. A productive loan spell with Wigan Athletic of the Championship saw him promoted to the Chelsea first team upon his return in 2019, after which he began to establish himself as a regular fixture at right-back and earn a long-term contract extension in January 2020. After representing England at various youth levels, James was called up to the full international side for the first time in October 2020, earning his first cap against Wales." 
            },
            {
                id: 6,
                img: "https://imgur.com/E60nEIy.png",
                name: "Ben Chilwell",
                nationality: "England",
                flag: "https://imgur.com/xTc0O2G.png",
                position: "Defender",
                birth: "21/12/1996 (24)",
                number: "21",
                appearances: "127",
                assists: "14",
                goals: "8",
                info: "Benjamin James Chilwell (born 21 December 1996) is an English professional footballer who plays as a left-back for Premier League club Chelsea and the England national team. Chilwell was born in Milton Keynes, Buckinghamshire, and attended Redborne Upper School and Community College." 
            },
            {
                id: 7,
                img: "https://imgur.com/Mzoyimr.png",
                name: "Antonio Rudiger",
                nationality: "Germany",
                flag: "https://imgur.com/YVysNAx.png",
                position: "Defender",
                birth: "03/03/1993 (28)",
                number: "2",
                appearances: "106",
                assists: "1",
                goals: "7",
                info: "Antonio Rüdiger (born 3 March 1993) is a German professional footballer who plays as a centre-back for Premier League club Chelsea and the Germany national team. Rüdiger began his career at VfB Stuttgart, representing their reserves in 3. Liga and the first team in the Bundesliga. In 2015 he joined Roma, initially on loan and a year later for a €9 million fee. He was signed by Chelsea in 2017 for an estimated £27 million, where he won the FA Cup in his first season, followed by the UEFA Europa League in his second season, and the UEFA Champions League in 2021. He made his international debut for Germany in March 2014. He was forced to miss UEFA Euro 2016 due to an injury suffered earlier in the season but he was part of the squad that won the 2017 FIFA Confederations Cup. He kept his spot in the squad for the 2018 World Cup, and later also took part at UEFA Euro 2020." 
            },
            {
                id: 8,
                img: "https://imgur.com/su0ehJ4.png",
                name: "Trevoh Chalobah",
                nationality: "England",
                flag: "https://imgur.com/xTc0O2G.png",
                position: "Defender",
                birth: "05/07/1999 (22)",
                number: "14",
                appearances: "4",
                assists: "0",
                goals: "2",
                info: "Trevoh Tom Chalobah (born 5 July 1999) is an English professional footballer who plays as a centre-back or defensive midfielder for Premier League club Chelsea. Chalobah joined Chelsea in 2007 at the age of eight, joining his brother Nathaniel in the club's academy. He spent time out on loan at Ipswich Town, Huddersfield Town and French side Lorient. He made his senior debut for Chelsea in the 2021 UEFA Super Cup, helping the club lift the trophy following a penalty shoot-out win. He has represented England at various youth levels from U16 to U21 level. In 2017, he helped England win the 2017 UEFA European Under-19 Championship." 
            },
            {
                id: 9,
                img: "https://imgur.com/KA96pvI.png",
                name: "Thiago Silva",
                nationality: "Brazil",
                flag: "https://imgur.com/eVuXyN8.png",
                position: "Defender",
                birth: "22/09/1984 (37)",
                number: "6",
                appearances: "28",
                assists: "0",
                goals: "3",
                info: "Thiago Emiliano da Silva (born 22 September 1984), known as Thiago Silva, is a Brazilian professional footballer who plays as a centre back for Premier League club Chelsea and is the captain of the Brazil national team. He is considered to be one of the best central defenders of his generation. Silva began his senior club career in 2002 playing as a midfielder for RS Futebol, and transitioned to a defensive position while at Juventude; he then signed with Porto in 2004, at age 19, and moved to Dynamo Moscow on loan, where he was hospitalized with a near fatal bout of tuberculosis. After recovering, he joined Fluminense and won a Copa do Brasil. In 2009, Silva moved to AC Milan for a reported fee of €8 million and won a Serie A title. In 2012, Silva was the subject of a then-record association football transfer when he signed for Paris Saint-Germain in a transfer worth up to €42 million, becoming the most expensive defender ever at the time. There, he won seven Ligue 1 titles, six Coupes de la Ligue, five Coupes de France, and reached the UEFA Champions League final. Silva holds the record as the club's longest ever serving captain and ranks eight-highest all-time for appearances. In 2020, he signed for Chelsea on a free transfer, and won the UEFA Champions League. Silva made his senior international debut for Brazil in 2008, at age 23, and has since earned over 90 caps, including appearing in seven major tournaments. He won a bronze medal in the 2008 Olympics and a silver medal at the 2012 Olympics, and later served as captain as Brazil won the 2013 FIFA Confederations Cup and finished fourth at the 2014 FIFA World Cup. Silva later helped his country win the 2019 Copa América." 
            },
            {
                id: 10,
                img: "https://imgur.com/6mDy9FU.png",
                name: "Andreas Christensen",
                nationality: "Denmark",
                flag: "https://imgur.com/Jd3nq30.png",
                position: "Defender",
                birth: "10/04/1996 (25)",
                number: "4",
                appearances: "79",
                assists: "0",
                goals: "0",
                info: "Andreas Bødtker Christensen (born 10 April 1996) is a Danish professional footballer who plays as a centre-back for Premier League club Chelsea and the Denmark national team. Christensen began his career at Skjold Birkerød and later joined Brøndby. He joined Chelsea at the age of 15 in February 2012, making his professional debut in October 2014. From 2015 to 2017, he was loaned to Bundesliga club Borussia Mönchengladbach, where he made 82 appearances and scored 7 goals. Christensen made his full international debut for Denmark in June 2015, and represented the nation at the 2018 FIFA World Cup and UEFA Euro 2020." 
            },
            {
                id: 11,
                img: "https://imgur.com/SISZ7QQ.png",
                name: "Malang Sarr",
                nationality: "France",
                flag: "https://imgur.com/aPvcJcf.png",
                position: "Defender",
                birth: "23/01/1999 (22)",
                number: "31",
                appearances: "0",
                assists: "0",
                goals: "0",
                info: "Malang Mamadou William Georges Sarr (born 23 January 1999) is a French professional footballer who plays as a defender for Premier League club Chelsea. He has also represented France at youth international level. An academy graduate of Nice, he scored on his senior debut in 2016 and made over 100 appearances for the club." 
            },
            {
                id: 12,
                img: "https://imgur.com/leSNlWS.png",
                name: "Jorginho",
                nationality: "Italy",
                flag: "https://imgur.com/qo5zGNG.png",
                position: "Midfielder",
                birth: "20/12/1991 (29)",
                number: "5",
                appearances: "103",
                assists: "3",
                goals: "13",
                info: "Jorge Luiz Frello Filho Cavaliere OMRI (born 20 December 1991), known as Jorginho, is a professional footballer who plays as a midfielder for Premier League club Chelsea and the Italy national team. He operates as a defensive midfielder or a deep-lying playmaker, also known as a regista in Italian football. Born in Brazil, Jorginho moved to Italy at the age of 15, and began his professional career with the Verona youth team, before being promoted to the senior team. During the 2010–11 season, he was sent on loan to Sambonifacese. In January 2014, he moved to Napoli, where he soon after won the Coppa Italia and the Supercoppa Italiana. He totaled 160 games for the club before a £50 million move to Chelsea in 2018, where he won the UEFA Europa League in his first season, followed by the UEFA Champions League during the 2020–21 season. At international level, he has represented Italy, making his senior debut in 2016, while his competitive debut came the following year. He was part of the Italy squad which won UEFA Euro 2020. He was named to the Team of the Tournament for his performances, and was later named the 2021 UEFA Men's Player of the Year." 
            },
            {
                id: 13,
                img: "https://imgur.com/5l1PnTT.png",
                name: "N'Golo Kante",
                nationality: "France",
                flag: "https://imgur.com/aPvcJcf.png",
                position: "Midfielder",
                birth: "29/03/1991 (30)",
                number: "7",
                appearances: "198",
                assists: "12",
                goals: "11",
                info: "N'Golo Kanté (born 29 March 1991) is a French professional footballer who plays as a central midfielder for Premier League club Chelsea and the France national team. Considered by many to be one of the world's best midfielders, Kanté is widely praised for his work rate and defensive acumen. Kanté made his senior professional debut with Boulogne in 2012, appearing as a substitute in one Ligue 2 match, and played an entire season in the third division the following year. After that he joined Ligue 2 side Caen on a free transfer, finished third and won promotion to Ligue 1. He stayed with the club for one more year. In 2015, Kanté joined Leicester City for a fee worth £5.6 million and was integral to their maiden Premier League victory. The following year, he joined Chelsea for a fee worth £32 million and again won the league, making him the first outfield player to win consecutive English league titles with different clubs since Eric Cantona in 1992 and 1993. He has also won the PFA Players' Player of the Year and FWA Footballer of the Year, an FA Cup, the UEFA Europa League, and the UEFA Champions League. He was named the UEFA Men's Midfielder of the year in 2021. Kanté made his senior international debut for France in 2016 and was included in the squad that finished runners-up at the 2016 European Championship. In 2017 Kanté was named the French Player of the Year, a first for a player from the Premier League in seven years, and twelve months later was a key member of the 2018 FIFA World Cup winning squad." 
            },
            {
                id: 14,
                img: "https://imgur.com/tujqflE.png",
                name: "Mateo Kovacic",
                nationality: "Croatia",
                flag: "https://imgur.com/14Mn66G.png",
                position: "Midfielder",
                birth: "06/05/1994 (27)",
                number: "8",
                appearances: "97",
                assists: "9",
                goals: "2",
                info: "Mateo Kovačić (Croatian pronunciation: [matěo kǒʋatʃitɕ];[4][5] born 6 May 1994) is a Croatian professional footballer who plays as a midfielder for Premier League club Chelsea and the Croatia national team. He is usually deployed in a central or box-to-box role, but can play in deeper positions. He also adapted to playing either wide on the left or as an attacking midfielder earlier in his career. Kovačić began his professional career with Dinamo Zagreb at the age of 16, with whom he won two consecutive league titles, before joining Inter Milan in 2013. After the 2014–15 season, he moved to Real Madrid, where he won the 2015–16, 2016–17 and 2017–18 Champions League. He joined Chelsea on one-year loan in 2018, winning the 2018–19 Europa League in the process and eventually signing permanently for the Premier League club. After the 2019–20 season, he was named Chelsea Player of the Year. A full Croatian international since 2013, Kovačić represented the nation at the 2014 FIFA World Cup, UEFA Euro 2016, the 2018 FIFA World Cup and UEFA Euro 2020, reaching the final of the 2018 tournament. He was nicknamed Il Professore (The Professor) by the Italian sports journalists."  
            },
            {
                id: 15,
                img: "https://imgur.com/lSKs5Ht.png",
                name: "Mason Mount",
                nationality: "England",
                flag: "https://imgur.com/xTc0O2G.png",
                position: "Midfielder",
                birth: "10/01/1999 (22)",
                number: "19",
                appearances: "78",
                assists: "11",
                goals: "13",
                info: "Mason Tony Mount (born 10 January 1999) is an English professional footballer who plays as an attacking or central midfielder for Premier League club Chelsea and the England national team. Mount began his senior club career with Chelsea. He joined Vitesse and Derby County on consecutive loans between 2017 and 2019; he established himself as an integral player for Chelsea in the following years, and won the UEFA Champions League and the UEFA Super Cup in 2021. Mount won the UEFA European Under-19 Championship with the England national under-19 team in 2017. He made his senior international debut in 2019, at age 20, and was part of the England team at UEFA Euro 2020." 
            },
            {
                id: 16,
                img: "https://imgur.com/JtR3XPb.png",
                name: "Ruben Loftus-Cheek",
                nationality: "England",
                flag: "https://imgur.com/xTc0O2G.png",
                position: "Midfielder",
                birth: "23/01/1996 (25)",
                number: "12",
                appearances: "110",
                assists: "7",
                goals: "10",
                info: "Ruben Ira Loftus-Cheek (born 23 January 1996) is an English professional footballer who plays as a midfielder for Premier League club Chelsea, and the England national team. Loftus-Cheek was born in Lewisham, Greater London. He grew up and attended school in Swanley, Kent. Loftus-Cheek is of Guyanese descent. He is the half-brother, on his father's side, of former professional footballers Carl and Leon Cort. His younger brother, Joe, is a semi-professional footballer."  
            }, 
            {
                id: 17,
                img: "https://imgur.com/kGHnHuo.png",
                name: "Ross Barkley",
                nationality: "England",
                flag: "https://imgur.com/xTc0O2G.png",
                position: "Midfielder",
                birth: "05/12/1993 (27)",
                number: "18",
                appearances: "227",
                assists: "28",
                goals: "28",
                info: "Ross Barkley (born 5 December 1993) is an English professional footballer who plays as an attacking midfielder for Premier League club Chelsea and the England national team. Barkley began his professional career at Everton in 2010. After loan spells at Sheffield Wednesday and Leeds United he became a regular in their team, playing 179 total games and scoring 27 goals for Everton. He signed for Chelsea in 2018 and won the FA Cup in 2018 and UEFA Europa League in 2019. Barkley made his full international debut in 2013. He played for England at the 2014 FIFA World Cup and was selected in Roy Hodgson's 23-man squad for UEFA Euro 2016 but did not appear in any of England's matches. Managers and teammates have compared his style of play to those of Michael Ballack, Paul Gascoigne and Wayne Rooney." 
            },
            {
                id: 18,
                img: "https://imgur.com/1UELU8m.png",
                name: "Saul Niguez",
                nationality: "Spain",
                flag: "https://imgur.com/AFxTnIn.png",
                position: "Midfielder",
                birth: "21/11/1994 (26)",
                number: "17",
                appearances: "1",
                assists: "0",
                goals: "0",
                info: "Saúl Ñíguez Esclápez (born 21 November 1994), known as Saúl, is a Spanish professional footballer who plays as a central or defensive midfielder for Premier League club Chelsea, on loan from Atlético Madrid of La Liga, and the Spain national team. After coming through Atlético Madrid's youth academy, Saúl went on to appear in more than 300 competitive matches for the club. In the 2013–14 season, he was on loan at Rayo Vallecano, also in La Liga. Having represented Spain at various youth levels, Saúl helped the under-21 team finish second in the 2017 UEFA European Under-21 Championship, being top scorer in the process. He was selected by the senior team for the 2018 FIFA World Cup."
            },
            {
                id: 19,
                img: "https://imgur.com/ohu0UrB.png",
                name: "Kai Havertz",
                nationality: "Germany",
                flag: "https://imgur.com/YVysNAx.png",
                position: "Forward",
                birth: "11/06/1999 (22)",
                number: "29",
                appearances: "33",
                assists: "3",
                goals: "5",
                info: "Kai Lukas Havertz (born 11 June 1999) is a German professional footballer who plays as an attacking midfielder for Premier League club Chelsea and the Germany national team. Starting off his career with Alemannia Mariadorf's youth academy, Havertz was promoted to Bayer Leverkusen's first team in 2016 after playing for his hometown club Alemannia Aachen and Leverkusen's youth system. Upon making his debut for the latter in 2016, Havertz became the club's youngest-ever debutant in the Bundesliga, and he became their youngest-ever goalscorer when he scored his first goal the following year. He is also the youngest player to reach the milestones of 50 and 100 league appearances in the German top flight. With Chelsea, he won the 2020–21 UEFA Champions League, scoring the only goal in the final against Manchester City." 
            },
            {
                id: 20,
                img: "https://imgur.com/KZmaEWO.png",
                name: "Romelu Lukaku",
                nationality: "Belgium",
                flag: "https://imgur.com/Ts3g4Y4.png",
                position: "Forward",
                birth: "13/05/1993 (28)",
                number: "9",
                appearances: "258",
                assists: "35",
                goals: "116",
                info: "Romelu Menama Lukaku Bolingoli (Dutch pronunciation: [ˈroːmeːlu luˈkaːku]; born 13 May 1993) is a Belgian professional footballer who plays as a striker for Premier League club Chelsea and the Belgium national team. Lukaku began his senior club career playing for Anderlecht, where he won a Belgian Pro League title and finished as the league's top goalscorer. In 2011, he joined Chelsea in a transfer worth £10 million (€12 million), but limited playing time resulted in loans to West Bromwich Albion and Everton; in 2014, Lukaku signed with Everton in a then club-record transfer worth £28 million (€32 million), going onto finish as the league's second-top goalscorer. He subsequently signed with Manchester United in a transfer worth £75 million (€88 million), but after a breakdown in relations with the club, Lukaku departed for Inter Milan in 2019 in a club-record deal worth €80 million (£68.1 million), and won a Serie A title and Serie A Most Valuable Player. In 2021, Lukaku returned to Chelsea in a club-record transfer worth £97.5 million (€115 million), becoming the seventh-most expensive player, the most expensive Belgian player, and the most expensive player with reference to cumulative transfer fees. Belgium's all-time top goalscorer, Lukaku made his senior international debut in 2010, and has represented his country at four major tournaments: the 2016 and 2020 UEFA European Championships and the 2014 and 2018 FIFA World Cups; he finished as joint second-highest goalscorer won the Bronze Boot in the latter." 
            },
            {
                id: 21,
                img: "https://imgur.com/CFbAFRL.png",
                name: "Christian Pulisic",
                nationality: "United States",
                flag: "https://imgur.com/R5pqczl.png",
                position: "Forward",
                birth: "18/09/1998 (23)",
                number: "10",
                appearances: "53",
                assists: "6",
                goals: "14",
                info: "Christian Mate Pulisic (/ˈmɑːteɪ pəˈlɪsɪk, ˈpʊlɪʃɪtʃ/; Croatian: Pulišić, pronounced [krǐstijan mǎːte pǔliʃitɕ]; born September 18, 1998) is an American professional soccer player who plays as a winger or an attacking midfielder for Premier League club Chelsea and the United States national team. Due to his high level of play along with his nationality, he has been given the nickname 'Captain America' by fans and other players. Pulisic began his professional career at German club Borussia Dortmund, where, after fast progression through the team's youth academy, in which he featured in only 15 youth games, he was promoted to the senior team in 2016, at age 17. He featured sparingly in his first season at the club, but his involvement increased dramatically in the following campaign, where he was a mainstay in the Dortmund team that won the 2016–17 DFB-Pokal. In 2018, he finished second in the inaugural Kopa Trophy, given to the best player under age 21. In January 2019, Pulisic moved to Chelsea in a transfer worth $73 million (£57.6 million), making him the most expensive North American player of all time, and began playing for the club in the 2019–20 season. Pulisic has scored 16 goals in 38 games as a United States international player. He has appeared and scored at every youth level and made his senior team debut in March 2016 at age 17. He is the youngest player ever to captain the United States national team in the modern era. He helped the U.S. to the final of the 2019 CONCACAF Gold Cup, and has won a U.S. Soccer Young Male Athlete of the Year award, two U.S. Soccer Male Athlete of the Year awards, and a UEFA Champions League winners medal."
            },
            {
                id: 22,
                img: "https://imgur.com/uXRl2d3.png",
                name: "Hakim Ziyech",
                nationality: "Morocco",
                flag: "https://imgur.com/qNoeoY5.png",
                position: "Forward",
                birth: "19/03/1993 (28)",
                number: "22",
                appearances: "25",
                assists: "3",
                goals: "2",
                info: "Hakim Ziyech (Arabic: حكيم زياش‎); (Tamazight: ⵃⴰⴽⵉⵎ ⵣⵉⵢⴰⵛ); born 19 March 1993) is a professional footballer who plays as an attacking midfielder or winger for Premier League club Chelsea and the Morocco national team. Ziyech is known for his finishing, dribbling, long passes, technique, and ability from free kicks. In 2019, he was selected as one of the 20 best players in the UEFA Champions League for the 2018–19 season. At the end of the same year, he was ranked 29th in The Guardian's list of 'The 100 best footballers in the world'. Ziyech started his professional career at Dutch club Heerenveen in 2012 and signed for fellow Dutch club Twente two years later. In 2016 he signed for Ajax on a five-year deal, with a reported transfer fee of €11m. The 2018–19 season was the most prolific season in Ziyech's career, as he scored 16 goals and provided 13 assists in the Eredivisie. He joined Premier League club Chelsea for the 2020–21 season. Originally eligible to play for the Netherlands or Morocco at international level, he has represented Morocco at the 2018 FIFA World Cup and the 2019 Africa Cup of Nations."
            },
            {
                id: 23,
                img: "https://imgur.com/wVxidOu.png",
                name: "Callum Hudson-Odoi",
                nationality: "England",
                flag: "https://imgur.com/xTc0O2G.png",
                position: "Forward",
                birth: "07/11/2000 (20)",
                number: "20",
                appearances: "59",
                assists: "9",
                goals: "3",
                info: "Callum James Hudson-Odoi (born 7 November 2000) is an English professional footballer who plays as a winger for Premier League club Chelsea and the England national team. During his time with Chelsea's academy, Hudson-Odoi was part of the squads which won the U18 Premier League in 2017 as well as back-to-back FA Youth Cup titles. His form at youth level was rewarded in January 2018 when he was handed his senior debut and he has since made over 90 appearances for the club. Hudson-Odoi also enjoyed considerable success at youth level for England, being part of the squad which ended as runners-up in the UEFA European Under-17 Championship and which won the FIFA U-17 World Cup in the same year. In March 2019, he became the youngest player to debut in a competitive match for England, doing so in UEFA Euro 2020 qualifiers against the Czech Republic."
            },
            {
                id: 24,
                img: "https://imgur.com/V6TipOT.png",
                name: "Timo Werner",
                nationality: "Germany",
                flag: "https://imgur.com/YVysNAx.png",
                position: "Forward",
                birth: "06/03/1996 (25)",
                number: "11",
                appearances: "41",
                assists: "9",
                goals: "7",
                info: "Timo Werner (German pronunciation: [ˈtiːmoː ˈvɛɐ̯nɐ]; born 6 March 1996) is a German professional footballer who plays as a forward for Premier League club Chelsea and the Germany national team. Werner began his senior club career in 2013 playing for VfB Stuttgart, becoming the club's youngest debutant and youngest ever goalscorer. He signed with RB Leipzig in 2016, aged 20, in a then club record transfer worth €10 million, where he set the record as the youngest player to reach 150 and 200 appearances in the Bundesliga. Werner also finished as the league's second highest goalscorer in the 2019–20 season. After becoming Leipzig's all-time top goalscorer, Werner departed to Chelsea in 2020 for €50 million, lifting the UEFA Champions League in his first season at the club. A German international, Werner was a prolific goalscorer at youth international level for Germany, scoring 34 goals in 48 appearances across the various age group levels. Werner made his senior debut in 2017 and helped Germany win the 2017 FIFA Confederations Cup, winning the Golden Boot as the tournament's highest goalscorer. He also represented Germany at the 2018 FIFA World Cup and UEFA Euro 2020."
            },
        ]
    })
}